# Generated by Django 3.2.18 on 2023-04-24 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
